name: valorant_store_viewer
description: "App to see your today's store in valorant"
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  mobx: ^2.5.0
  flutter_mobx: ^2.2.1+1
  flutter_modular: ^6.3.4
  window_manager: ^0.4.3
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mobx_codegen: ^2.7.0
  build_runner: ^2.1.0

flutter:

  uses-material-design: true
  assets:
  - assets/

